#+title: Common documentation
#+author: Nicholas Vollmer

* Preamble                                                         :noexport:
This document contains documentation included in the README file as well as the Info manual.
In order to export after saving changes, evaluate the following source blocks:

#+begin_src emacs-lisp :lexical t :results silent
(require 'ox-gfm)
(defun +elpaca-export-readme ()
  (with-current-buffer (find-file-noselect "./readme.org")
    (org-export-to-file 'gfm "../README.md")))
(add-hook 'after-save-hook #'+elpaca-export-readme nil t)

(require 'ox-texinfo)
(defun +elpaca-export-manual ()
  (with-current-buffer (find-file-noselect "./manual.org")
    (org-export-to-file 'texinfo "./elpaca.texi")))
(add-hook 'after-save-hook #'+elpaca-export-manual nil t)

(defun +elpaca-export-md ()
  (with-current-buffer (find-file-noselect "./manual.org")
    (org-export-to-file 'gfm "./manual.md")))
(add-hook 'after-save-hook #'+elpaca-export-md nil t)

(add-hook 'after-save-hook #'org-babel-tangle nil t)
#+end_src

* Introduction
:PROPERTIES:
:CUSTOM_ID: introduction
:END:
Elpaca is an elisp package manager.
It allows users to find, install, update, and remove third-party packages for Emacs.
It is a replacement for the built-in Emacs package manager, package.el.
* Installation
:PROPERTIES:
:DESCRIPTION: Installing Elpaca.
:CUSTOM_ID: installation
:END:
** Requirements
:PROPERTIES:
:DESCRIPTION: The required software environment for Elpaca.
:CUSTOM_ID: installation-requirements
:END:
Elpaca requires:
- Emacs >= 27.1
- git (minimum version TBD)
** Installer
:PROPERTIES:
:CUSTOM_ID: installer
:DESCRIPTION: A script responsible for installing Elpaca.
:END:
To install Elpaca, add the following elisp to your init.el.
It must come before any calls to other Elpaca functions/macros.
This will clone Elpaca into your =user-emacs-directory= under the =elpaca= subdirectory.
It then builds and activates Elpaca.

#+begin_src emacs-lisp :lexical t :eval never-export :tangle "./init.el" :exports none
;; Example Elpaca configuration -*- lexical-binding: t; -*-
#+end_src

#+begin_src emacs-lisp :lexical t :eval never-export :tangle "./init.el"
(defvar elpaca-installer-version 0.6)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (call-process "git" nil buffer t "clone"
                                       (plist-get order :repo) repo)))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))
#+end_src

- Windows users must be able to create symlinks[fn:1], or enable =elpaca-no-symlink-mode=

#+begin_src emacs-lisp :lexical t :eval never-export :tangle "./init.el"
;; Uncomment for systems which cannot create symlinks:
;; (elpaca-no-symlink-mode)
#+end_src

You'll also want to disable package.el in your early-init file[fn:2]:

#+begin_src emacs-lisp :lexical t :tangle "./early-init.el" :eval never-export :exports none
;; Example Elpaca early-init.el -*- lexical-binding: t; -*-
#+end_src

#+begin_src emacs-lisp :lexical t :tangle "./early-init.el" :eval never-export
(setq package-enable-at-startup nil)
#+end_src

#+begin_src emacs-lisp :lexical t :tangle "./early-init.el" :eval never-export :exports none
;; Local Variables:
;; no-byte-compile: t
;; no-native-compile: t
;; no-update-autoloads: t
;; End:
#+end_src

And remove anything related to package.el in your init file. e.g. calls to ~(package-activate-all)~.

* Quick Start
:PROPERTIES:
:CUSTOM_ID: quick-start
:END:

| Operation                             | UI (keys apply in elpaca-ui-mode) | completing-read interface commands               |
|---------------------------------------+-----------------------------------+--------------------------------------------------|
| Finding Packages                      | ~M-x elpaca-manager~                | ~elpaca-try~                                       |
| Trying Packages (for current session) | ~i~ ~x~                               | ~elpaca-try~                                       |
| Fetching Package Updates              | ~f~ ~x~                               | ~elpaca-fetch~ or ~elpaca-fetch-all~                 |
| Merging Updates                       | ~u~ ~x~                               | ~elpaca-merge~ or ~elpaca-merge-all~                 |
| Pulling Updates^*                     | ~C-u u~ ~x~                           | ~C-u M-x~ ~elpaca-merge~ or ~C-u M-x~ ~elpaca-merge-all~ |
| Rebuilding Packages                   | ~r~ ~x~                               | ~elpaca-rebuild~                                   |
| Deleting Packages                     | ~d~ ~x~                               | ~elpaca-delete~                                    |
| View Package Logs                     | ~l~ filters log to current package  | ~elpaca-log~                                       |
| View Package Statuses                 | ~t~ show most recent log entries    | ~elpaca-status~                                    |
| Visit Package Repository Directory    | ~v~                                 | ~elpaca-visit~                                     |
| Visit Package Build Directory         | ~C-u~ ~v~                             | ~C-u M-x~ ~elpaca-visit~                             |
| Browse Package Website                | ~b~                                 | ~elpaca-browse~                                    |
|---------------------------------------+-----------------------------------+--------------------------------------------------|
​* It's encouraged to fetch, review, and *then* merge package updates rather than pulling.


Packages installed via the above commands are not loaded on subsequent Emacs sessions (after restarting).
To install and load packages persistently (across Emacs restarts), use the =elpaca= macro in your init file after the installer. ([[#installer][installer]])

For example:

#+begin_src emacs-lisp :lexical t :eval never-export :tangle "./init.el" :exports code
;; Install use-package support
(elpaca elpaca-use-package
  ;; Enable :elpaca use-package keyword.
  (elpaca-use-package-mode)
  ;; Assume :elpaca t unless otherwise specified.
  (setq elpaca-use-package-by-default t))

;; Block until current queue processed.
(elpaca-wait)

;;When installing a package which modifies a form used at the top-level
;;(e.g. a package which adds a use-package key word),
;;use `elpaca-wait' to block until that package has been installed/configured.
;;For example:
;;(use-package general :demand t)
;;(elpaca-wait)

;; Expands to: (elpaca evil (use-package evil :demand t))
(use-package evil :demand t)

;;Turns off elpaca-use-package-mode current declaration
;;Note this will cause the declaration to be interpreted immediately (not deferred).
;;Useful for configuring built-in emacs features.
(use-package emacs :elpaca nil :config (setq ring-bell-function #'ignore))

;; Don't install anything. Defer execution of BODY
(elpaca nil (message "deferred"))
#+end_src

#+begin_src emacs-lisp :lexical t :tangle "./init.el" :eval never-export :exports none
;; Local Variables:
;; no-byte-compile: t
;; no-native-compile: t
;; no-update-autoloads: t
;; End:
#+end_src

*IMPORTANT*:

Elpaca installs and activates packages asynchronously.
Elpaca processes its package queues /after/ Emacs reads the init file.[fn:3]
Consider the following example:

#+begin_src emacs-lisp :lexical t :eval never-export
(elpaca nil (message "First")) ; Queue First
(message "Second") ; Second messaged
(elpaca nil (message "Third")) ; Queue Third
(elpaca-process-queues) ; Process queue: First messaged, Third messaged.
#+end_src

"Second" will be message /before/ "First" and "Third".
Defer forms which are dependent on deferred forms.
Wrapping the "Second" message in an =elpaca= declaration will fix the above example:

#+begin_src emacs-lisp :lexical t :eval never-export
(elpaca nil (message "First"))  ; Queue First
(elpaca nil (message "Second")) ; Queue Second
(elpaca nil (message "Third"))  ; Queue Third
(elpaca-process-queues) ; Process queue: First, Second, Third messaged.
#+end_src

Add any configuration which relies on =after-init-hook=, =emacs-startup-hook=, etc to =elpaca-after-init-hook= so it runs after Elpaca has activated all queued packages.
This includes loading of saved customizations. e.g.

#+begin_src emacs-lisp :lexical t
(setq custom-file (expand-file-name "customs.el" user-emacs-directory))
(add-hook 'elpaca-after-init-hook (lambda () (load custom-file 'noerror)))
#+end_src

* Footnotes

[fn:1] [[https://www.howtogeek.com/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/][windows symlink guide]]

[fn:2] [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Early-Init-File.html][early-init file]]

[fn:3] This is so Elpaca can build a proper dependency tree. It ensures packages the user explicitly requests are not preempted by dependencies of other packages.
